name: Perform formatting checks

on:
 pull_request:
    branches: [release, master]

jobs:
  server-formatting:
    name: server-formatting
    uses: ./.github/workflows/formatting/server-spotless.yml
    secrets: inherit
    with:
      pr: ${{ github.event.pull_request.number }}

  client-formatting:
    name: client-formatting
    uses: ./.github/workflows/formatting/client-prettier.yml
    secrets: inherit
    with:
      pr: ${{ github.event.pull_request.number }}
